import { decryptSecret,encryptSecret } from "./crypto";
import type { createRequestClient } from "@/lib/supabase/server";

type Supabase=ReturnType<typeof createRequestClient>;
type Credentials={account_email:string;access_token_ciphertext:string|null;refresh_token_ciphertext:string|null;token_expires_at:string|null;scopes:string[];last_verified_at:string|null;last_error:string|null};
const oauthConfig=()=>{const clientId=process.env.GOOGLE_CLIENT_ID,clientSecret=process.env.GOOGLE_CLIENT_SECRET,redirectUri=process.env.GOOGLE_OAUTH_REDIRECT_URI;if(!clientId||!clientSecret||!redirectUri)throw new Error("Google OAuth is not configured.");return{clientId,clientSecret,redirectUri};};
export const gmailScopes=["https://www.googleapis.com/auth/gmail.readonly","openid","email"];
export function googleAuthorisationUrl(state:string){const{clientId,redirectUri}=oauthConfig(),params=new URLSearchParams({client_id:clientId,redirect_uri:redirectUri,response_type:"code",scope:gmailScopes.join(" "),access_type:"offline",prompt:"consent",include_granted_scopes:"true",state});return `https://accounts.google.com/o/oauth2/v2/auth?${params}`;}
export async function exchangeGoogleCode(code:string){const{clientId,clientSecret,redirectUri}=oauthConfig();const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:clientId,client_secret:clientSecret,redirect_uri:redirectUri,grant_type:"authorization_code"})});if(!response.ok)throw new Error(`Google token exchange failed (${response.status}).`);return response.json() as Promise<{access_token:string;refresh_token?:string;expires_in:number;scope:string}>;}
async function refresh(refreshToken:string){const{clientId,clientSecret}=oauthConfig();const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({refresh_token:refreshToken,client_id:clientId,client_secret:clientSecret,grant_type:"refresh_token"})});if(!response.ok)throw new Error(`Google token refresh failed (${response.status}).`);return response.json() as Promise<{access_token:string;expires_in:number;scope?:string}>;}
export async function gmailAccessToken(supabase:Supabase){const{data,error}=await supabase.rpc("get_gmail_credentials",{});if(error)throw error;const credentials=(data?.[0]??null) as Credentials|null;if(!credentials?.access_token_ciphertext)throw new Error("Gmail is not connected.");if(!credentials.token_expires_at||new Date(credentials.token_expires_at).getTime()>Date.now()+60000)return{token:decryptSecret(credentials.access_token_ciphertext),credentials};if(!credentials.refresh_token_ciphertext)throw new Error("Gmail access expired. Reconnect Gmail.");const fresh=await refresh(decryptSecret(credentials.refresh_token_ciphertext));const expiresAt=new Date(Date.now()+fresh.expires_in*1000).toISOString();await supabase.rpc("store_gmail_credentials",{account_email:credentials.account_email,access_token_ciphertext:encryptSecret(fresh.access_token),refresh_token_ciphertext:null,token_expires_at:expiresAt,scopes:credentials.scopes});return{token:fresh.access_token,credentials:{...credentials,token_expires_at:expiresAt}};}
export async function gmailFetch<T>(token:string,path:string){const response=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me${path}`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(`Gmail retrieval failed (${response.status}).`);return response.json() as Promise<T>;}
export async function gmailProfile(token:string){return gmailFetch<{emailAddress:string;historyId:string}>(token,"/profile");}
