"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Check,ExternalLink,Mail,RefreshCw,X } from "lucide-react";
import { EmptyState,Pill } from "@/components/ui";
import { createBrowserClient } from "@/lib/supabase/client";
import type { EmailThread,ImportProposal,JobEmailThread } from "@/types/database";

type ReviewData={links:JobEmailThread[];threads:EmailThread[];proposals:ImportProposal[]};
export function JobEmailReview({jobId}:{jobId:string}){const supabase=useMemo(()=>createBrowserClient(),[]),[data,setData]=useState<ReviewData|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[notes,setNotes]=useState<Record<string,string>>({}),[edits,setEdits]=useState<Record<string,unknown>>({}),[overrides,setOverrides]=useState<Record<string,boolean>>({});
const api=useCallback(async(path:string,options?:RequestInit)=>{const{data:session}=await supabase.auth.getSession();return fetch(path,{...options,headers:{"content-type":"application/json",...options?.headers,authorization:`Bearer ${session.session?.access_token??""}`}});},[supabase]);
const load=useCallback(async()=>{const response=await api(`/api/jobs/${jobId}/email`);setData(await response.json());},[api,jobId]);useEffect(()=>{load();},[load]);
async function sync(){setBusy(true);setNotice("Searching Gmail for corroborated job threads…");const response=await api(`/api/jobs/${jobId}/email/sync`,{method:"POST"}),body=await response.json();setNotice(body.ok?`Found ${body.candidates} candidate thread(s) and staged ${body.proposals} proposal(s).`:body.error);setBusy(false);load();}
async function review(link:JobEmailThread,status:"included"|"excluded"){await api(`/api/jobs/${jobId}/email`,{method:"PATCH",body:JSON.stringify({linkId:link.id,status})});setNotice(status==="included"?"Thread included for proposal review.":"Thread excluded; its evidence was retained.");load();}
async function decide(proposal:ImportProposal,action:"accept"|"reject"){const response=await api(`/api/jobs/${jobId}/email/proposals/${proposal.id}`,{method:"PATCH",body:JSON.stringify({action,editedValue:edits[proposal.id],note:notes[proposal.id]??null,confirmOverride:overrides[proposal.id]??false})}),body=await response.json();setNotice(body.message??body.error);if(body.requiresOverride)setNotice(`${body.message} Tick “Replace existing value” and add a decision note.`);load();}
if(!data)return <EmptyState icon={Mail} title="Loading email review" body="Checking staged Gmail evidence."/>;const thread=(id:string)=>data.threads.find(item=>item.id===id),included=new Set(data.links.filter(link=>link.review_status==="included").map(link=>link.email_thread_id));return <div className="email-review"><div className="section-head"><div><h2>Gmail import review</h2><p className="meta">Candidate matching and extraction are deterministic. Nothing is confirmed until you accept it.</p></div><button className="icon-text-button" onClick={sync} disabled={busy}><RefreshCw size={16}/> Find emails</button></div>{notice?<p className="notice">{notice}</p>:null}
<section><h3>Candidate threads</h3>{!data.links.length?<EmptyState icon={Mail} title="No candidates staged" body="Connect Gmail in Settings, then search this job."/>:<div className="email-thread-list">{data.links.map(link=>{const item=thread(link.email_thread_id),reasons=Array.isArray(link.match_reasons)?link.match_reasons.map(String):[];return <article key={link.id}><div><strong>{item?.subject??"Email thread"}</strong><small>{link.match_score}% match · {reasons.join(" · ")}</small><p>{item?.snippet}</p>{item?.gmail_url?<a href={item.gmail_url} target="_blank" rel="noreferrer">Open external Gmail reference <ExternalLink size={13}/></a>:null}</div><div className="review-actions"><button className={link.review_status==="included"?"active":"secondary-button"} onClick={()=>review(link,"included")}><Check size={15}/> Include</button><button className={link.review_status==="excluded"?"active":"secondary-button"} onClick={()=>review(link,"excluded")}><X size={15}/> Exclude</button></div></article>})}</div>}</section>
<section><h3>Proposed imports</h3><div className="proposal-list">{data.proposals.filter(proposal=>proposal.email_thread_id&&included.has(proposal.email_thread_id)).map(proposal=><article key={proposal.id} className={proposal.conflict_group?"has-conflict":""}><div className="proposal-head"><span><strong>{proposal.proposed_text}</strong><small>{proposal.field_key.replaceAll("_"," ")} · {Math.round(proposal.confidence*100)}% deterministic confidence</small></span><Pill tone={proposal.status==="accepted"?"good":proposal.status==="rejected"?"quiet":proposal.conflict_group?"warn":"neutral"}>{proposal.status==="pending"&&proposal.conflict_group?"Conflict":proposal.status}</Pill></div><blockquote>{proposal.source_excerpt}</blockquote>{proposal.status==="pending"?<><ProposalEditor proposal={proposal} value={edits[proposal.id]??proposal.proposed_value} onChange={value=>setEdits({...edits,[proposal.id]:value})}/><label>Decision note<input value={notes[proposal.id]??""} onChange={event=>setNotes({...notes,[proposal.id]:event.target.value})} placeholder="Optional unless replacing a confirmed value"/></label><label className="check-label"><input type="checkbox" checked={overrides[proposal.id]??false} onChange={event=>setOverrides({...overrides,[proposal.id]:event.target.checked})}/> Replace an existing confirmed value if needed</label><div className="review-actions"><button onClick={()=>decide(proposal,"accept")}><Check size={15}/> Accept edited value</button><button className="secondary-button" onClick={()=>decide(proposal,"reject")}><X size={15}/> Reject</button></div></>:<p className="resolution-text">{proposal.status}{proposal.decision_note?` · ${proposal.decision_note}`:""}</p>}</article>)}</div></section></div>}

function ProposalEditor({proposal,value,onChange}:{proposal:ImportProposal;value:unknown;onChange:(value:unknown)=>void}){const item=typeof value==="object"&&value?value as Record<string,unknown>:{};if(proposal.field_key.endsWith("_at"))return <label>Confirmed time<input type="time" value={String(item.time??"")} onChange={event=>onChange({time:event.target.value})}/></label>;if(proposal.field_key==="start_date")return <label>Confirmed date<input type="date" value={String(item.date??"")} onChange={event=>onChange({date:event.target.value})}/></label>;if(proposal.field_key==="contact")return <div className="proposal-fields"><label>Contact name<input value={String(item.name??"")} onChange={event=>onChange({...item,name:event.target.value})}/></label><label>Phone<input value={String(item.phone??"")} onChange={event=>onChange({...item,phone:event.target.value})}/></label></div>;if(proposal.field_key==="pack_item")return <div className="proposal-fields"><label>Equipment<input value={String(item.name??"")} onChange={event=>onChange({...item,name:event.target.value})}/></label><label>Quantity<input type="number" min="1" value={Number(item.quantity??1)} onChange={event=>onChange({...item,quantity:Number(event.target.value)})}/></label></div>;if(proposal.field_key==="site_note")return <label>Confirmed site detail<textarea value={String(item.text??"")} onChange={event=>onChange({...item,text:event.target.value})}/></label>;if(["venue","programme_notes","technical_notes","open_question"].includes(proposal.field_key))return <label>Confirmed text<textarea value={String(value??"")} onChange={event=>onChange(event.target.value)}/></label>;return <p className="meta">{proposal.field_key==="document"?"This attached file will keep its original filename and source.":"Review this structured requirement before accepting it."}</p>}
