import { describe, expect, it } from "vitest";
import { calculateReadiness, effectiveStatusGate, evaluateStatusGate } from "@/lib/readiness";
import type { Job, PackItem } from "@/types/database";
const job = { id:"job",title:"Fixture",client_id:"client",primary_contact_id:null,venue:"Town Hall",start_at:null,end_at:null,date_precision:"date",start_date:"2026-10-01",end_date:"2026-10-01",event_date:"2026-10-01",status:"planning",brief:"A real brief",intent:null,google_calendar_event_id:null,source_email_thread_id:null,precedent_job_id:null,readiness:0,contact_name:null,contact_email:null,arrival_at:null,bump_in_at:null,setup_at:null,soundcheck_at:null,bump_out_at:null,programme_notes:null,technical_notes:null,status_override_reason:null,status_override_at:null,status_override_by:null,quoted_value:null,quote_reference:null,invoice_reference:null,quote_status:null,invoice_status:null,source:null,lost_reason:null,archived_at:null,site_notes:{},tags:[],created_at:"2026-01-01",updated_at:"2026-01-01" } satisfies Job;
describe("operational readiness",()=>{
  it("uses one calculation and identifies packing blockers",()=>{const result=calculateReadiness(job,[],[]);expect(result.score).toBe(67);expect(result.blockers).toEqual(["Arrival or access","Pack list"]);expect(evaluateStatusGate("ready_to_pack",result)).toEqual({allowed:false,blockers:["Arrival or access","Pack list"],requiresOverride:true});});
  it("allows ready-to-pack when access and a planned item exist",()=>{const pack=[{quantity_planned:1} as PackItem];expect(evaluateStatusGate("ready_to_pack",calculateReadiness({...job,arrival_at:"2026-10-01T00:00:00Z"},[],pack)).allowed).toBe(true);});
  it("does not allow Packed until every planned quantity is packed",()=>{const pack=[{quantity_planned:2,quantity_packed:1} as PackItem],readiness=calculateReadiness({...job,arrival_at:"2026-10-01T00:00:00Z"},[],pack);expect(evaluateStatusGate("ready_to_pack",readiness).allowed).toBe(true);expect(evaluateStatusGate("packed",readiness).blockers).toContain("All planned quantities packed");});
  it("requires an explicit override reason",()=>{const readiness=calculateReadiness(job,[],[]);expect(effectiveStatusGate("ready_to_pack",readiness,"").allowed).toBe(false);expect(effectiveStatusGate("ready_to_pack",readiness,"Proceed for warehouse prep").overridden).toBe(true);});
});
