"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Bot,CalendarDays,Link2Off,Mail,RefreshCw,ShieldCheck } from "lucide-react";
import { Pill,Section } from "@/components/ui";
import { createBrowserClient } from "@/lib/supabase/client";
import type { TeamMember } from "@/types/database";

type GmailStatus={configured:boolean;authenticated:boolean;retrieval:boolean;sync:boolean;account?:string;lastSyncedAt?:string|null;message?:string};
export default function SettingsPage(){const supabase=useMemo(()=>createBrowserClient(),[]),[member,setMember]=useState<TeamMember|null>(null),[gmail,setGmail]=useState<GmailStatus|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
const api=useCallback(async(path:string,options?:RequestInit)=>{const{data}=await supabase.auth.getSession();return fetch(path,{...options,headers:{...options?.headers,authorization:`Bearer ${data.session?.access_token??""}`}});},[supabase]);
const load=useCallback(async()=>{const[memberResult,status]=await Promise.all([supabase.from("team_members").select("*").maybeSingle(),api("/api/integrations/gmail/status")]);setMember(memberResult.data??null);setGmail(await status.json());},[api,supabase]);useEffect(()=>{load();},[load]);
async function connect(){setBusy(true);const response=await api("/api/integrations/gmail/connect",{method:"POST"}),body=await response.json();if(body.url)window.location.href=body.url;else{setNotice(body.error??"Could not start connection.");setBusy(false);}}
async function disconnect(){setBusy(true);const response=await api("/api/integrations/gmail/disconnect",{method:"POST"}),body=await response.json();setNotice(body.ok?"Gmail disconnected.":body.error);setBusy(false);load();}
return <main className="page"><header className="page-head"><div><p className="eyebrow">Workspace</p><h1>Settings</h1><p>Authentication, retrieval and sync are reported separately.</p></div></header>{notice?<p className="notice">{notice}</p>:null}<Section title="Team access"><div className="settings-row"><ShieldCheck size={20}/><span><strong>{member?.display_name??"Signed-in member"}</strong><small>{member?.role??"Checking access"} · Supabase Auth and RLS</small></span><Pill tone="good">Active</Pill></div></Section>
<Section title="Connections"><div className="settings-list">
<div className="settings-row integration-row"><Mail size={20}/><span><strong>Gmail</strong><small>{!gmail?"Checking connection…":!gmail.configured?gmail.message:gmail.authenticated?`${gmail.account} · retrieval verified${gmail.sync?` · last sync ${new Date(gmail.lastSyncedAt!).toLocaleString("en-AU")}`:" · no job sync completed"}`:gmail.message??"Not authenticated"}</small><div className="connection-stages"><Pill tone={gmail?.authenticated?"good":"quiet"}>Auth {gmail?.authenticated?"working":"off"}</Pill><Pill tone={gmail?.retrieval?"good":"quiet"}>Retrieval {gmail?.retrieval?"working":"off"}</Pill><Pill tone={gmail?.sync?"good":"quiet"}>Sync {gmail?.sync?"working":"not run"}</Pill></div></span>{gmail?.authenticated?<button className="secondary-button" onClick={disconnect} disabled={busy}><Link2Off size={16}/> Disconnect</button>:<button className="icon-text-button" onClick={connect} disabled={busy||gmail?.configured===false}><Mail size={16}/> Connect</button>}</div>
<div className="settings-row"><CalendarDays size={20}/><span><strong>Google Calendar</strong><small>Calendar uses confirmed Timbre Ops job dates. Google Calendar is not connected.</small></span><Pill>Not connected</Pill></div>
<div className="settings-row"><Bot size={20}/><span><strong>AI interpretation</strong><small>Deterministic extraction and commands only. No AI interpreter is connected.</small></span><Pill>Not connected</Pill></div>
</div></Section><button className="text-action" onClick={load}><RefreshCw size={15}/> Recheck connections</button></main>}
