"use client";
import { use,useEffect,useMemo,useState } from "react";
import Image from "next/image";
import { createBrowserClient } from "@/lib/supabase/client";
import { formatDateTime,formatJobSchedule,statusLabel } from "@/lib/format";
import { isPlanDocument,jobPackContents } from "@/lib/job-pack";
import type { Client,ExternalLink,ImportProposal,Job,JobChange,JobDocument,JobRequirement,PackItem } from "@/types/database";

export default function JobPackPage({params}:{params:Promise<{id:string}>}){
  const{id}=use(params),supabase=useMemo(()=>createBrowserClient(),[]);const[job,setJob]=useState<Job|null>(null),[client,setClient]=useState<Client|null>(null),[items,setItems]=useState<PackItem[]>([]),[changes,setChanges]=useState<JobChange[]>([]),[requirements,setRequirements]=useState<JobRequirement[]>([]),[documents,setDocuments]=useState<JobDocument[]>([]),[links,setLinks]=useState<ExternalLink[]>([]),[proposals,setProposals]=useState<ImportProposal[]>([]),[signedUrls,setSignedUrls]=useState<Record<string,string>>({});
  useEffect(()=>{Promise.all([supabase.from("jobs").select("*").eq("id",id).single(),supabase.from("pack_items").select("*").eq("job_id",id).order("item_name"),supabase.from("job_changes").select("*").eq("job_id",id).order("created_at",{ascending:false}),supabase.from("job_requirements").select("*").eq("job_id",id),supabase.from("job_documents").select("*").eq("job_id",id).order("created_at"),supabase.from("external_links").select("*").eq("job_id",id),supabase.from("import_proposals").select("*").eq("job_id",id).eq("status","pending")]).then(async([a,b,c,d,e,f,g])=>{setJob(a.data);setItems(b.data??[]);setChanges(c.data??[]);setRequirements(d.data??[]);setDocuments(e.data??[]);setLinks(f.data??[]);setProposals(g.data??[]);if(a.data?.client_id){const clientResult=await supabase.from("clients").select("*").eq("id",a.data.client_id).maybeSingle();setClient(clientResult.data);}const urls:Record<string,string>={};for(const doc of e.data??[]){if(doc.storage_path){const result=await supabase.storage.from("job-files").createSignedUrl(doc.storage_path,900);if(result.data?.signedUrl)urls[doc.id]=result.data.signedUrl;}}setSignedUrls(urls);});},[id,supabase]);
  if(!job)return <main className="job-pack"><p>Loading job pack…</p></main>;
  const content=jobPackContents({job,client,pack:items,changes,requirements,documents,links}),site=job.site_notes&&typeof job.site_notes==="object"&&!Array.isArray(job.site_notes)?job.site_notes:{};
  const scheduleValue=(field:string,value:string|null)=>value?formatDateTime(value):proposals.some(item=>item.field_key===field)?"Not confirmed · proposal awaiting review":"Not recorded";
  const schedule=[["Job date",formatJobSchedule(job)],["Arrival / access",scheduleValue("arrival_at",job.arrival_at)],["Bump-in",scheduleValue("bump_in_at",job.bump_in_at)],["Setup",scheduleValue("setup_at",job.setup_at)],["Soundcheck",scheduleValue("soundcheck_at",job.soundcheck_at)],["Event start",job.date_precision==="timed"?scheduleValue("start_at",job.start_at):proposals.some(item=>item.field_key==="start_at")?"Date only · time proposal awaiting review":"Date only · time not confirmed"],["Event end",job.date_precision==="timed"?scheduleValue("end_at",job.end_at):proposals.some(item=>item.field_key==="end_at")?"Date only · time proposal awaiting review":"Date only · time not confirmed"],["Bump-out / clear",scheduleValue("bump_out_at",job.bump_out_at)]];
  return <main className="job-pack"><header><p>Timbre Pro Audio · Operational Job Pack</p><h1>{job.title}</h1><p>{formatJobSchedule(job)} · {job.venue??"Venue TBC"}</p><p className="pack-generated">Generated {new Intl.DateTimeFormat("en-AU",{dateStyle:"medium",timeStyle:"short"}).format(new Date())}</p></header>
    <section><h2>Brief and intent</h2><p>{job.brief??"No brief recorded."}</p>{job.intent?<p><strong>Intent:</strong> {job.intent}</p>:null}</section>
    <section><h2>Schedule</h2><dl className="pack-facts">{schedule.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
    <section><h2>On-day contacts</h2><dl className="pack-facts"><div><dt>Primary contact</dt><dd>{job.contact_name??client?.name??"Not recorded"}</dd></div><div><dt>Email</dt><dd>{job.contact_email??client?.email??"Not recorded"}</dd></div><div><dt>Phone</dt><dd>{String(site.on_day_phone??client?.phone??"Not recorded")}</dd></div></dl></section>
    <section><h2>Venue and access</h2><p><strong>Venue:</strong> {job.venue??"Not recorded"}</p><p><strong>Access:</strong> {String(site.access??"Not recorded")}</p><p><strong>FOH / operations:</strong> {String(site.foh??"Not recorded")}</p><p><strong>Cable runs:</strong> {String(site.cable_runs??"Not recorded")}</p></section>
    <section><h2>Technical details</h2>{job.technical_notes?<p>{job.technical_notes}</p>:null}{["power","pa_coverage","projection","signal_data"].map(key=><p key={key}><strong>{statusLabel(key)}:</strong> {String(site[key]??"Not recorded")}</p>)}</section>
    <section><h2>Programme, performers and changeovers</h2><p>{job.programme_notes??(proposals.some(item=>item.field_key==="programme_notes")?"Programme found in source material and awaiting confirmation.":"No confirmed programme recorded.")}</p></section>
    <section><h2>Pack checklist</h2>{items.length?<table><thead><tr><th>Item</th><th>Planned</th><th>Packed</th><th>Out</th><th>Returned</th><th>Notes</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>□ {item.item_name}</td><td>{item.quantity_planned}</td><td>{item.quantity_packed}</td><td>{item.quantity_out}</td><td>{item.quantity_returned}</td><td>{item.notes}</td></tr>)}</tbody></table>:<p>No pack items recorded. This job is not ready to pack.</p>}</section>
    <section><h2>Outstanding questions</h2>{content.unresolved.length?<ul>{content.unresolved.map(item=><li key={item.id}><strong>{item.summary}</strong>{item.detail?`: ${item.detail}`:""}</li>)}</ul>:<p>No unresolved attention items.</p>}{requirements.filter(item=>item.applicable&&!item.resolved).map(item=><p key={item.id}>□ {item.label}{item.detail?` — ${item.detail}`:""}</p>)}</section>
    <section><h2>Plans and attachments</h2>{documents.length?<ul>{documents.map(doc=><li key={doc.id}>{doc.name} · {doc.mime_type??statusLabel(doc.category)} · source {statusLabel(doc.source)}{signedUrls[doc.id]?<a href={signedUrls[doc.id]} target="_blank" rel="noreferrer"> Open attachment</a>:" · unavailable"}</li>)}</ul>:<p>No files are attached to this job.</p>}{links.length?<><h3>External references</h3><ul>{links.map(link=><li key={link.id}>{statusLabel(link.provider)} external reference · not included in this pack</li>)}</ul></>:null}</section>
    {documents.filter(isPlanDocument).map(doc=><section className="plan-page" key={doc.id}><h2>{doc.name}</h2>{doc.mime_type?.startsWith("image/")&&signedUrls[doc.id]?<Image src={signedUrls[doc.id]} alt={doc.name} width={1200} height={800} unoptimized/>:<><p>This plan exists as a referenced attachment but cannot be embedded in the printed pack.</p>{signedUrls[doc.id]?<a href={signedUrls[doc.id]} target="_blank" rel="noreferrer">Open {doc.name}</a>:null}</>}</section>)}
    <button className="print-button" onClick={()=>window.print()}>Print job pack</button>
  </main>;
}
