"use client";
import { use,useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { ArrowLeft,Check,Download,ExternalLink as ExternalIcon,FileText,Minus,Plus,Printer,Trash2,Upload } from "lucide-react";
import { EmptyState,Pill } from "@/components/ui";
import { JobEmailReview } from "@/components/job-email-review";
import { attentionResolutionPatch } from "@/lib/attention";
import { formatDateTime,formatJobSchedule,statusLabel } from "@/lib/format";
import { calculateReadiness,evaluateStatusGate } from "@/lib/readiness";
import { classifyDebriefLine } from "@/lib/memory";
import { jobStatuses,packStates } from "@/lib/status";
import { createBrowserClient } from "@/lib/supabase/client";
import type { Client,ExternalLink,Job,JobChange,JobDebrief,JobDocument,JobMemory,JobRequirement,PackItem } from "@/types/database";

const tabs=["overview","site","pack","files","email","changes","debrief"] as const;type Tab=(typeof tabs)[number];
export default function JobDetailPage({params}:{params:Promise<{id:string}>}){
 const{id}=use(params),supabase=useMemo(()=>createBrowserClient(),[]);const[job,setJob]=useState<Job|null>(null),[clients,setClients]=useState<Client[]>([]),[changes,setChanges]=useState<JobChange[]>([]),[pack,setPack]=useState<PackItem[]>([]),[links,setLinks]=useState<ExternalLink[]>([]),[requirements,setRequirements]=useState<JobRequirement[]>([]),[documents,setDocuments]=useState<JobDocument[]>([]),[debriefs,setDebriefs]=useState<JobDebrief[]>([]),[memories,setMemories]=useState<JobMemory[]>([]),[tab,setTab]=useState<Tab>("overview"),[notice,setNotice]=useState(""),[newPack,setNewPack]=useState(""),[debrief,setDebrief]=useState(""),[blockedStatus,setBlockedStatus]=useState<Job["status"]|null>(null),[overrideReason,setOverrideReason]=useState(""),[resolutionDrafts,setResolutionDrafts]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{const[a,b,c,d,e,f,g,h,i]=await Promise.all([supabase.from("jobs").select("*").eq("id",id).single(),supabase.from("clients").select("*").order("name"),supabase.from("job_changes").select("*").eq("job_id",id).order("created_at",{ascending:false}),supabase.from("pack_items").select("*").eq("job_id",id).order("item_name"),supabase.from("external_links").select("*").eq("job_id",id),supabase.from("job_requirements").select("*").eq("job_id",id),supabase.from("job_documents").select("*").eq("job_id",id).order("created_at",{ascending:false}),supabase.from("job_debriefs").select("*").eq("job_id",id).order("created_at",{ascending:false}),supabase.from("job_memories").select("*").eq("job_id",id).order("created_at",{ascending:false})]);setJob(a.data);setClients(b.data??[]);setChanges(c.data??[]);setPack(d.data??[]);setLinks(e.data??[]);setRequirements(f.data??[]);setDocuments(g.data??[]);setDebriefs(h.data??[]);setMemories(i.data??[]);},[id,supabase]);
 useEffect(()=>{load();const q=new URLSearchParams(window.location.search).get("tab");if(tabs.includes(q as Tab))setTab(q as Tab);},[load]);
 if(!job)return <main className="page"><Link href="/jobs"><ArrowLeft size={16}/> Jobs</Link><EmptyState icon={FileText} title="Job not available" body="Check access or the job link."/></main>;
 const currentJob=job,readiness=calculateReadiness(currentJob,requirements,pack),client=clients.find(c=>c.id===currentJob.client_id),site=(currentJob.site_notes??{}) as Record<string,string>;
 async function save(patch:Partial<Job>,message="Job saved"){const next:Job={...currentJob,...patch};setJob(next);const result=await supabase.from("jobs").update({...patch,readiness:calculateReadiness(next,requirements,pack).score}).eq("id",id);setNotice(result.error?.message??message);if(!result.error)await supabase.from("activity_log").insert({job_id:id,action:"job.updated",summary:`${currentJob.title} details updated`,source:"cameron",metadata:{fields:Object.keys(patch)}});load();}
 async function updatePack(item:PackItem,patch:Partial<PackItem>){setPack(p=>p.map(x=>x.id===item.id?{...x,...patch}:x));const r=await supabase.from("pack_items").update(patch).eq("id",item.id);if(r.error){setNotice(r.error.message);load();}}
 async function addPack(){if(!newPack.trim())return;await supabase.from("pack_items").insert({job_id:id,item_name:newPack.trim(),quantity_planned:1});setNewPack("");load();}
 async function upload(file:File){setNotice(`Uploading ${file.name}…`);const path=`${id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await supabase.storage.from("job-files").upload(path,file);if(up.error){setNotice(`Upload failed: ${up.error.message}`);return;}const record=await supabase.from("job_documents").insert({job_id:id,name:file.name,category:file.type.startsWith("image/")?"photo":"document",storage_path:path,mime_type:file.type,size_bytes:file.size,source:"cameron"});if(record.error){await supabase.storage.from("job-files").remove([path]);setNotice(`Upload metadata failed: ${record.error.message}`);return;}setNotice(`${file.name} uploaded.`);load();}
 async function openDocument(doc:JobDocument){if(doc.external_url){window.open(doc.external_url,"_blank","noopener");return;}if(doc.storage_path){const{data}=await supabase.storage.from("job-files").createSignedUrl(doc.storage_path,300);if(data?.signedUrl)window.open(data.signedUrl,"_blank","noopener");}}
 async function removeDocument(doc:JobDocument){if(!window.confirm(`Remove ${doc.name}? This cannot be undone.`))return;setNotice(`Removing ${doc.name}…`);if(doc.storage_path){const removed=await supabase.storage.from("job-files").remove([doc.storage_path]);if(removed.error){setNotice(`Removal failed: ${removed.error.message}`);return;}}const result=await supabase.from("job_documents").delete().eq("id",doc.id);setNotice(result.error?`Removal failed: ${result.error.message}`:`${doc.name} removed.`);load();}
 async function resolve(change:JobChange){const resolution=resolutionDrafts[change.id]?.trim();if(!resolution){setNotice("Record the resolution or remaining follow-up before marking reviewed.");return;}const{data}=await supabase.auth.getUser();const result=await supabase.from("job_changes").update(attentionResolutionPatch(resolution,data.user?.id??null)).eq("id",change.id);setNotice(result.error?.message??"Attention item reviewed; history retained.");load();}
 async function saveDebrief(){if(!debrief.trim())return;const{data,error}=await supabase.from("job_debriefs").insert({job_id:id,raw_text:debrief,source:"cameron"}).select().single();if(error){setNotice(error.message);return;}const lines=debrief.split(/\n|\./).map(x=>x.trim()).filter(Boolean);await supabase.from("job_memories").insert(lines.map(line=>({job_id:id,client_id:currentJob.client_id,debrief_id:data.id,category:classifyDebriefLine(line),summary:line,source:"cameron" as const})));setDebrief("");load();}
 async function attemptStatus(status:Job["status"]){const gate=evaluateStatusGate(status,readiness);if(!gate.allowed){setBlockedStatus(status);setOverrideReason("");setNotice(`Cannot move to ${statusLabel(status)} yet: ${gate.blockers.join(", ")}.`);return;}await save({status,status_override_reason:null,status_override_at:null,status_override_by:null},"Status updated.");}
 async function applyOverride(){if(!blockedStatus||!overrideReason.trim()){setNotice("An override reason is required.");return;}const{data}=await supabase.auth.getUser();await save({status:blockedStatus,status_override_reason:overrideReason.trim(),status_override_at:new Date().toISOString(),status_override_by:data.user?.id??null},"Status updated with a recorded override.");setBlockedStatus(null);setOverrideReason("");}
 async function updateMemory(memory:JobMemory,patch:Partial<JobMemory>){const result=await supabase.from("job_memories").update(patch).eq("id",memory.id);setNotice(result.error?.message??"Lesson updated.");load();}
 async function removeMemory(memory:JobMemory){if(!window.confirm("Remove this saved lesson?"))return;const result=await supabase.from("job_memories").delete().eq("id",memory.id);setNotice(result.error?.message??"Lesson removed.");load();}
 return <main className="page job-detail"><header className="job-header"><div><Link className="back-link" href="/jobs"><ArrowLeft size={15}/> Jobs</Link><h1>{job.title}</h1><p>{formatJobSchedule(job)}{job.venue?` · ${job.venue}`:""}</p></div><div className="job-head-actions"><Pill tone="good">{statusLabel(job.status)}</Pill><Link aria-label="Print job pack" title="Print job pack" href={`/jobs/${id}/pack`}><Printer size={19}/></Link></div></header>
 <section className="readiness-panel"><div><span>Readiness</span><strong>{readiness.score}%</strong></div><div className="progress"><i style={{width:`${readiness.score}%`}}/></div><p>{readiness.blockers.length?`Still needs: ${readiness.blockers.join(", ")}`:"Core operational details are ready."}</p></section>
 <nav className="detail-tabs" aria-label="Job sections">{tabs.map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} type="button" key={item}>{statusLabel(item)}</button>)}</nav>{notice?<p className="notice">{notice}</p>:null}
 {tab==="overview"?<section className="detail-layout"><div className="detail-section"><div className="section-head"><h2>Job brief</h2><button onClick={()=>save({brief:job.brief,intent:job.intent})} type="button">Save</button></div><label>Brief<textarea value={job.brief??""} onChange={e=>setJob({...job,brief:e.target.value})}/></label><label>Intent / scale<textarea value={job.intent??""} onChange={e=>setJob({...job,intent:e.target.value})}/></label></div><div className="detail-section"><h2>Core details</h2><label>Status<select value={blockedStatus??job.status} onChange={e=>attemptStatus(e.target.value as Job["status"])}>{jobStatuses.map(s=><option value={s} key={s}>{statusLabel(s)}</option>)}</select></label>{blockedStatus?<div className="gate-warning"><strong>Status gate blocked</strong><span>{evaluateStatusGate(blockedStatus,readiness).blockers.join(", ")}</span><label>Override reason<textarea value={overrideReason} onChange={e=>setOverrideReason(e.target.value)} placeholder="Why is it operationally safe to proceed?"/></label><div className="review-actions"><button onClick={applyOverride} type="button">Record override</button><button className="secondary-button" onClick={()=>setBlockedStatus(null)} type="button">Cancel</button></div></div>:null}{job.status_override_reason?<div className="override-note"><strong>Status override recorded</strong><span>{job.status_override_reason}</span></div>:null}<label>Date precision<select value={job.date_precision} onChange={e=>setJob({...job,date_precision:e.target.value as Job["date_precision"]})}><option value="date">Date only</option><option value="timed">Event time known</option></select></label>{job.date_precision==="date"?<label>Event date<input type="date" value={job.start_date??""} onChange={e=>setJob({...job,start_date:e.target.value||null})} onBlur={()=>save({date_precision:job.date_precision,start_date:job.start_date})}/></label>:<label>Event start<input type="datetime-local" value={toLocal(job.start_at)} onChange={e=>setJob({...job,start_at:e.target.value?new Date(e.target.value).toISOString():null})} onBlur={()=>save({date_precision:job.date_precision,start_at:job.start_at})}/></label>}<label>Venue<input value={job.venue??""} onChange={e=>setJob({...job,venue:e.target.value})} onBlur={()=>save({venue:job.venue})}/></label><label>Client<select value={job.client_id??""} onChange={e=>save({client_id:e.target.value||null})}><option value="">Not linked</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="contact-block"><strong>{client?.name??"No client linked"}</strong><span>{client?.email??"No email"}{client?.phone?` · ${client.phone}`:""}</span></div></div></section>:null}
 {tab==="site"?<section className="detail-section"><h2>Site & technical discovery</h2><div className="schedule-grid"><label>Arrival / access<input type="datetime-local" value={toLocal(job.arrival_at)} onChange={e=>setJob({...job,arrival_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label>Bump-in<input type="datetime-local" value={toLocal(job.bump_in_at)} onChange={e=>setJob({...job,bump_in_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label>Setup<input type="datetime-local" value={toLocal(job.setup_at)} onChange={e=>setJob({...job,setup_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label>Soundcheck<input type="datetime-local" value={toLocal(job.soundcheck_at)} onChange={e=>setJob({...job,soundcheck_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label>{job.date_precision==="timed"?<><label>Event start<input type="datetime-local" value={toLocal(job.start_at)} onChange={e=>setJob({...job,start_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label>Event end<input type="datetime-local" value={toLocal(job.end_at)} onChange={e=>setJob({...job,end_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label></>:<div className="date-only-note"><strong>Event date only</strong><span>No event start or end time is confirmed.</span></div>}<label>Bump-out / site clear<input type="datetime-local" value={toLocal(job.bump_out_at)} onChange={e=>setJob({...job,bump_out_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label></div><label>Programme notes<textarea value={job.programme_notes??""} onChange={e=>setJob({...job,programme_notes:e.target.value})}/></label><label>Technical notes<textarea value={job.technical_notes??""} onChange={e=>setJob({...job,technical_notes:e.target.value})}/></label><div className="field-grid">{["power","cable_runs","foh","access","pa_coverage","projection","signal_data"].map(key=><label key={key}>{statusLabel(key)}<textarea value={site[key]??""} onChange={e=>setJob({...job,site_notes:{...site,[key]:e.target.value}})}/></label>)}</div><button onClick={()=>save({site_notes:job.site_notes,arrival_at:job.arrival_at,bump_in_at:job.bump_in_at,setup_at:job.setup_at,soundcheck_at:job.soundcheck_at,start_at:job.date_precision==="timed"?job.start_at:null,end_at:job.date_precision==="timed"?job.end_at:null,bump_out_at:job.bump_out_at,programme_notes:job.programme_notes,technical_notes:job.technical_notes},"Schedule and site details saved")} type="button">Save site details</button></section>:null}
 {tab==="pack"?<section className="detail-section"><div className="section-head"><div><h2>Pack list</h2><p>Tap quantities as equipment moves through the job.</p></div></div><div className="inline-add"><input placeholder="Add pack item" value={newPack} onChange={e=>setNewPack(e.target.value)}/><button onClick={addPack} aria-label="Add pack item" title="Add pack item"><Plus size={18}/></button></div><div className="pack-list">{pack.map(item=><article className="pack-row" key={item.id}><div><strong>{item.item_name}</strong><select value={item.state} onChange={e=>updatePack(item,{state:e.target.value as PackItem["state"]})}>{packStates.map(s=><option value={s} key={s}>{statusLabel(s)}</option>)}</select></div><div className="quantity-strip">{(["quantity_planned","quantity_packed","quantity_out","quantity_returned"] as const).map(field=><div key={field}><span>{statusLabel(field.replace("quantity_",""))}</span><div><button onClick={()=>updatePack(item,{[field]:Math.max(0,item[field]-1)})} aria-label={`Decrease ${field}`}><Minus size={14}/></button><strong>{item[field]}</strong><button onClick={()=>updatePack(item,{[field]:item[field]+1})} aria-label={`Increase ${field}`}><Plus size={14}/></button></div></div>)}</div>{item.quantity_out>item.quantity_returned?<p className="discrepancy">{item.quantity_out-item.quantity_returned} still outstanding</p>:null}</article>)}</div></section>:null}
 {tab==="files"?<section className="detail-section"><div className="section-head"><div><h2>Files & external references</h2><p>Uploaded files are private. Gmail links below are references only; Gmail is not synced.</p></div><label className="upload-button"><Upload size={17}/> Upload file<input hidden type="file" accept=".pdf,image/*,.txt" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div><div className="document-list">{documents.map(doc=><article className="document-row" key={doc.id}><FileText size={19}/><span><strong>{doc.name}</strong><small>{doc.mime_type??statusLabel(doc.category)} · {doc.size_bytes?formatBytes(doc.size_bytes):"Size unavailable"} · uploaded {formatDateTime(doc.created_at)} · source {statusLabel(doc.source)}</small></span><button onClick={()=>openDocument(doc)} title={`Download ${doc.name}`} aria-label={`Download ${doc.name}`}><Download size={16}/></button><button onClick={()=>removeDocument(doc)} title={`Remove ${doc.name}`} aria-label={`Remove ${doc.name}`}><Trash2 size={16}/></button></article>)}{!documents.length?<p className="empty-inline">No files uploaded.</p>:null}{links.map(link=><a className="document-row" href={link.external_url??"#"} target="_blank" rel="noreferrer" key={link.id}><ExternalIcon size={19}/><span><strong>{statusLabel(link.provider)} external reference</strong><small>{link.external_id} · not synchronised</small></span></a>)}</div></section>:null}
 {tab==="changes"?<section className="detail-section"><h2>Changes & attention history</h2><div className="change-stream">{changes.map(change=><article key={change.id}><span className="source-mark">{change.source[0].toUpperCase()}</span><span><strong>{change.summary}</strong><small>{change.detail}</small><small>{formatDateTime(change.created_at)} · {statusLabel(change.source)}</small>{change.resolved_at?<small className="resolution-text">Resolution: {change.resolution??"Reviewed"} · {formatDateTime(change.resolved_at)}</small>:null}{change.requires_attention&&!change.resolved_at?<label className="resolution-field">Resolution / remaining follow-up<input value={resolutionDrafts[change.id]??""} onChange={e=>setResolutionDrafts({...resolutionDrafts,[change.id]:e.target.value})}/></label>:null}</span>{change.requires_attention&&!change.resolved_at?<button onClick={()=>resolve(change)} title="Mark reviewed" aria-label="Mark reviewed"><Check size={16}/></button>:change.resolved_at?<Pill tone="good">Reviewed</Pill>:null}</article>)}</div></section>:null}
 {tab==="debrief"?<section className="detail-section"><h2>Debrief & memory</h2><p>Write naturally. Classification is deterministic and can be corrected below.</p><textarea className="debrief-input" value={debrief} onChange={e=>setDebrief(e.target.value)} placeholder="What worked? What changes next time? Any equipment issues or purchase ideas?"/><button onClick={saveDebrief} type="button">Save debrief</button><div className="memory-list">{memories.map(memory=><article key={memory.id}><select aria-label={`Classification for ${memory.summary}`} value={memory.category} onChange={e=>updateMemory(memory,{category:e.target.value as JobMemory["category"]})}><option value="keep">Keep</option><option value="change_next_time">Change next time</option><option value="equipment_issue">Equipment issue</option><option value="missing_gear">Missing gear</option><option value="client_follow_up">Client follow-up</option><option value="purchase_idea">Purchase idea</option><option value="technical_lesson">Technical lesson</option><option value="general">General</option></select><input aria-label="Lesson" value={memory.summary} onChange={e=>setMemories(items=>items.map(item=>item.id===memory.id?{...item,summary:e.target.value}:item))} onBlur={()=>updateMemory(memory,{summary:memories.find(item=>item.id===memory.id)?.summary??memory.summary})}/><button onClick={()=>removeMemory(memory)} title="Remove lesson" aria-label="Remove lesson"><Trash2 size={16}/></button></article>)}</div>{!memories.length?<p className="empty-inline">No saved lessons yet.</p>:null}{debriefs.length?<p className="meta">{debriefs.length} original debrief{debriefs.length===1?"":"s"} retained.</p>:null}</section>:null}
 {tab==="email"?<section className="detail-section"><JobEmailReview jobId={id}/></section>:null}
 </main>;
}
function toLocal(value:string|null){if(!value)return"";const d=new Date(value),local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function formatBytes(bytes:number){if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${Math.round(bytes/1024)} KB`;return`${(bytes/1048576).toFixed(1)} MB`}
